package com.example.tengyu.lifeholder.tomato;

/**
 * Created by tengyu on 2015/12/22.
 */
public class tomatoNotes {
        public static int LENGTH = 148;
        public static String sntArray[]= new String[]{
                "Have an aim in life,or your energies will all be wasted.",
                "Living without an aim is like sailing without a compass.",
                "It matters not how a man dies,but how he lives.",
                "He who sees through life and death will meet with most success.",
                "Nothing is impossible to a willing heart.",
                "The secret of success is constancy of purpose.",
                "He that can have patience,can have what he will.",
                "A good name is easier lost than won.",
                "Self-distrust is the cause of most of our failures.",
                "I'm capable of achieving all my goals.",
                "I can do great things.",
                "If you want knowledge, you must toil for it.",
                "Never too old to learn.",
                "Doubt is the key of knowledge.",
                "Pursue breakthroughs in your life.",
                "I can change the world.",
                "Practice makes perfect.",
                "I know that my future is not just a dream.",
                "the shortest answer is doing.",
                "while there is life, there is hope.",
                "you have my whole-hearted support.",
                "No pain, no gain.",
                "Better late than never.",
                "I think you should go ahead.",
                "If at first you don't succeed,try,try,and try again.",
                "Nothing is impossible for a willing heart.",
                "Storms make trees take deeper roots.",
                "Thats better than i can do.",
                "Pain past is pleasure.",
                "All things are difficult before they are easy.",
                "Cheer up! our troubles will soon be over.",
                "Don’t lose heart, whatever happens.",
                "God helps those who help themselves.",
                "Great hopes make great man.",
                "I believe you can improve it.",
                "Two heads are better than one.",
                "You must welcome challenges if you want to be successful." ,
                "You’ll make it through whatever comes along .",
                "Because of your smile,you make life more beautiful.",
                "Count your blessings, not your trouble.",
                "Don’t take things too seriously.",
                "Good company on the road is the shortest cut.",
                "I’m the best！I’m the greatest！I’m invincible.",
                "Succeeding takes time.",
                "Be patient with yourself.",
                "Take the days just one at a time.",
                "The longer one carries a problem, the heavier it gets .",
                "The shortest answer is doing.",
                "There are no secrets to success.",
                "There is only one me in this world.",
                "Time flies.",
                "Time is money.",
                "Time and tide wait for no man.",
                "Time tries all.",
                "Time tries truth.",
                "Time past cannot be called back again.",
                "All time is no time when it is past.",
                "No one can call back yesterday.",
                "Yesterday will not be called again.",
                "Tomorrow comes never.",
                "One today is worth two tomorrows.",
                "The morning sun never lasts a day.",
                "Christmas comes but once a year.",
                "Pleasant hours fly past.",
                "Happiness takes no account of time.",
                "Time tames the strongest grief.",
                "The day is short but the work is much.",
                "Never deter till tomorrow that which you can do today.",
                "Have you somewhat to do tomorrow， do it today.",
                "To save time is to lengthen life.",
                "Everything has its time and that time must be watched.",
                "Take time when time comes lest time steal away.",
                "When an opportunity is neglected， it never comes back to you.",
                "Make hay while the sun shines.",
                "Strike while the iron is hot.",
                "Punctuality is the soul of business.",
                "Procrastination is the thief of time.",
                "Every tide has its ebb.",
                "Knowledge is power.",
                "Wisdom is more to be envied than riches.",
                "Wisdom is better than gold or silver.",
                "Wisdom in the mind is better than money in the hand.",
                "Wisdom is a good purchase though we pay dear for it.",
                "Doubt is the key of knowledge.",
                "If you want knowledge， you must toil for it.",
                "A little knowledge is a dangerous thing.",
                "A handful of common sense is worth a bushel of learning.",
                "Knowledge advances by steps and not by leaps.",
                "Learn wisdom by the follies of others.",
                "It is good to learn at another man's cost.",
                "Wisdom is to the mind what health is to the body.",
                "Experience is the best teacher.",
                "Experience is the father of wisdom and memory the mother.",
                "Dexterity comes by experience.",
                "Practice makes perfect.",
                "Experience keeps a dear school， but fools learn in no other.",
                "Wit once bought is worth twice taught.",
                "Seeing is believing.",
                ",Business is the salt of life.",
                "Business before pleasure.",
                "Business makes a man as well as tries him.",
                "Business neglected is business lost.",
                "Never think yourself above business.",
                "Business may be troublesome， but idleness is pernicious.",
                "Do business， but be not a slave to it.",
                "Everybody's business is nobody's business.",
                "Work makes the workman.",
                "Better master one than engage with ten.",
                "A work ill done must be twice done.",
                "They who cannot do as they would， must do as they can.",
                "If you would have a thing well done， do it yourself.",
                "He that doth most at once doth least.",
                "Do as most men do and men will speak well of thee.",
                "What may be done at any time will be done at no time.",
                "Better late than never.",
                "Whatever is worth doing at all is worth doing well.",
                "The shortest answer is doing the thing.",
                "Action is the proper fruit of knowledge.",
                "Finished labours are pleasant.",
                "It is lost labour to sow where there is no soil.",
                "It is right to put everything in its proper use.",
                "Affairs that are done by due degrees are soon ended.",
                ",All work and no play makes Jack a dull boy.",
                "Work bears witness who does well.",
                "It is not work that kills， but worry.",
                "He that will not work shall not eat.",
                "Put your shoulder to the wheel.",
                "Never do things by halves.",
                "In for a penny， in for a pound.",
                "A bad workman quarrels with his tools.",
                "Diligence is the mother of success.",
                "Idleness is the root of all evil.",
                "Care and diligence bring luck.",
                "Diligence is the mother of good fortune.",
                "Industry is fortune's right hand，and frugality her left.",
                "Idleness is the key of beggary.",
                "No root， no fruit.",
                "Sloth is the key of poverty.",
                "Sloth tarnishes the edge of wit.",
                "An idle brain is the devil's workshop.",
                "The secret of wealth lies in the letters SAVE.",
                "An idle youth， a needy age.",
                "There is only one me in this world.",
                "I'm on the top of the world.",
                "I'm ready for any challenge.",
                "The future is in my hands.",
                "It's totally up to me.",
                "I'm born to succeed."};
}
